site_name: From Idea to Deployment - Understanding Development Best Practices
repo_url: "https://github.com/lmicek/LMICEK-ATO-2024"
edit_uri: "edit/main/docs/"
dev_addr: "0.0.0.0:8000"
use_directory_urls: false
extra:
  generator: false
nav:
  - Home:
      - index.md
      - intro.md
      - planning.md
      - environment.md
      - coding.md
      - testing.md
      - documentation.md
      - deployment.md
      - conclusion.md
  - LinkedIn: https://www.linkedin.com/in/lauramicek
  - GitHub: https://github.com/lmicek
  - ATO: https://2024.allthingsopen.org/
markdown_extensions:
  - def_list
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      toc_depth: 2-4
      title: On this page
      anchorlink: true
  - pymdownx.magiclink
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - markdown_include.include:
      base_path: .
theme:
  name: material
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.path
    - search.share
    - search.suggest
    - content.action.view
    - content.code.copy
    - toc.integrate
plugins:
  - external-markdown
  - awesome-pages
  - glightbox
  - include-markdown
  - table-reader
  - markdownextradata
  - mkdocs-video
  - pagenav-generator
  - search
  - tags
  - open-in-new-tab
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
